### ISSUE TITLE
BoundingBox with upperLeft and lowerRight

### ISSUE THREAD

**Issue by FranzBusch** [timsearle/Euclid#1]
Hi,

Quick question do you know the bearings for using upperLeft and lowerRight coordinates instead of the lowerLeft and upperRight ones?

**Comment by timsearle** [comment]
Hi! Sorry it has taken me a while to respond. Could you clarify whether you want support for bounding box creation from upperLeft and lowerRight? Or you want to be able to obtain the calculated values of upperLeft and lowerRight?

**Comment by FranzBusch** [comment]
Hey! Already figured it out. I just wanted to use the upperLeft and lowerRight to init the BoundingBox, but to do that I just had to change the bearings to 135 and 315 :)

**Comment by timsearle** [comment]
Ah! Glad you got it sorted. Let me know once you have finished your project and I'd be happy to add it to a list on the README of apps using the framework!
